name: Build and Deploy backend prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to nora-prod server
    runs-on: Nora-Prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP with required extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # change to match your environment
          extensions: curl

      - name: Copy app files to new server
        run: |
          sudo rsync -a --delete ./ /var/www/nora-backend-prod/

      # Uncomment and modify if you need to replace .env during deploy
      # - name: Replace env file
      #   run: |
      #     sudo rm -f /var/www/nora-backend-prod/.env
      #     sudo cp /path/to/env/.env.prod /var/www/nora-backend-prod/.env

      - name: Composer install and set permissions
        run: |
          export COMPOSER_ALLOW_SUPERUSER=1
          cd /var/www/nora-backend-prod
          sudo composer update --with-all-dependencies
          sudo chown -R www-data:www-data /var/www/nora-backend-prod
