name: Build and Deploy backend prodAdd commentMore actions

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    name: Deploy to nora-prod serverAdd commentMore actions
    runs-on: Nora-Prod
    # labels:
    #   - nojom-app 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy app files to new server
        run: |
          sudo rsync -a --delete ./ /var/www/nora-backend-prod/

      - name: Replace env file
        run: |
          sudo mv /var/www/nora-backend-prod/.env.example /var/www/nora-backend-prod/.env

      - name: Composer install and set permissions
        run: |
          sudo bash -c "cd /var/www/nora-backend-prod && composer install  --working-dir=/var/www/nora-backend-prod/ && php artisan key:generate"
          sudo chown -R www-data:www-data /var/www/nora-backend-prod
